name: Linux release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [x64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        echo "Setting up environment for ${{ matrix.arch }}"
        if [ "${{ matrix.arch }}" == "x64" ]; then
          echo "TARGET_ARCH=x86_64" >> $GITHUB_ENV
        elif [ "${{ matrix.arch }}" == "arm64" ]; then
          echo "TARGET_ARCH=arm64" >> $GITHUB_ENV
        fi

    - name: Build and Test
      run: |
        chmod +x ./build_and_test.sh
        ./build_and_test.sh

    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Extract files and build DEB package
      run: |
        chmod +x ./build_deb.sh
        ./build_deb.sh ${{ steps.vars.outputs.tag }}

    - name: Rename binaries
      run: |
        echo "Renaming binaries to include architecture"
        mv /app/build/bazelbin/src/starkware/main/cpu/cpu_air_prover ./cpu_air_prover-linux-${TARGET_ARCH}
        mv /app/build/bazelbin/src/starkware/main/cpu/cpu_air_verifier ./cpu_air_verifier-linux-${TARGET_ARCH}
        mv /tmp/stone-prover/stone-prover.deb /tmp/stone-prover/stone-prover-linux-${TARGET_ARCH}.deb


    - name: Upload files to a GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: ./cpu_air*

    - name: Upload dep to a GitHub release
      id: create_release_deb
      uses: softprops/action-gh-release@v2
      with:
        files: /tmp/stone-prover/stone-prover-linux-${TARGET_ARCH}.deb
