name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        arch: [x64, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        if [ "${{ matrix.arch }}" == "x64" ]; then
          export TARGET_ARCH="x86_64"
        elif [ "${{ matrix.arch }}" == "arm64" ]; then
          export TARGET_ARCH="arm64"
        fi

    - name: Build binary
      run: |
        chmod +x ./build_mac.sh
        ./build_mac.sh # Replace this with your build command

    - name: Rename binary
      run: |
        mv /tmp/stone-prover/build/bazelbin/src/starkware/main/cpu/cpu_air_prover ./cpu_air_prover-macOS-${TARGET_ARCH}
        mv /tmp/stone-prover/build/bazelbin/src/starkware/main/cpu/cpu_air_verifier ./cpu_air_verifier-macOS-${TARGET_ARCH}

    - name: Upload files to a GitHub release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: ./cpu_air*

